name: mics_client_sdk
description: MICS client SDK for Flutter/Dart (WebSocket + Protobuf binary).
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cryptography: ^2.7.0
  fixnum: ^1.1.1
  protobuf: ^6.0.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
