apiVersion: v1
kind: Service
metadata:
  name: mics-gateway-headless
  labels:
    app: mics-gateway
spec:
  clusterIP: None
  selector:
    app: mics-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080

